### PR TITLE
Yet another round of proofreading

### PR DESCRIPTION
**Pull request by eriktorbjorn**
Since I didn't accidentally break your repository with my last pull request, here's today's report. :-)

Only whitespace fixes this time around, and sometimes it's a bit hard to tell how many spaces there really are. But hopefully I got them right. (And I know you'll double-check them anyway.) I was more worried about errors in the map data, but I didn't find any.

### CODE REVIEW

**Comment by Quuxplusone** [comment]
All look good to me! I'm counting this as 6 errata, btw, but that matches the number of commits you made, so I think you'll agree with my reasoning. :) Bug bounties incoming!

**Comment by eriktorbjorn** [comment]
Yeah, I did briefly consider making separate commits for them but decided that it would be silly for a systematic error. Incidentally, I made the exact same error myself on one of the lines at first.

**Comment by Quuxplusone** [comment]
> Yeah, I did briefly consider making separate commits for them but decided that it would be silly for a systematic error.

And I'm a cheapskate. ;) But also, once you pointed out one of them, of course I _had_ to check the other nine lines myself anyway. So if you'd missed one of those, I would have found it anyway. As opposed to the bulk of the errors you're finding, which I never would have found without making a lot of effort myself.

I did find another data-file mistake myself today: `runnel` for `tunnel` in `long.dat` (now fixed and squashed in main). Probably a lot of easy pickings left in there, though.

**Comment by eriktorbjorn** [comment]
> And I'm a cheapskate. ;)

Hmm... Not according to my PayPal wallet. :-) By the way, the typos in the data file you mentioned are probably the ones I'm going to be most likely to miss myself once I get there. I hope you'll be able to find more proofreaders. I know David Griffith over at the intfiction.org forums expressed an interest in porting the game to Inform 6, so maybe he'll spot some more.

I imagine people behind blogs like "Renga in Blue" and "Data Driven Gamer" might be interested in playing the game, and I also stumbled over a reddit thread where someone seemed to be asking about this very game... eight years ago. I wonder if it's still possible to post replies: https://www.reddit.com/r/tipofmytongue/comments/zn4z1/tomtcomputer_game_haunted_mansionstyle_text/

Edit: I just realized that the guy I think runs the Renga in Blue blog already tweeted about this game, and that you had already posted about the reddit thread. Oh well. :-)

**Pull request closed without merging**
